### ISSUE TITLE
https://www.solidjs.com/guides/getting-started page linked to 404 docs.

### ISSUE THREAD

**Issue by shinebayar-g** [solidjs/solid-docs-next#187]
> We're working on new docs. You can check out our new beginner tutorial [**here**](https://docs.solidjs.com/tutorials/getting-started-with-solid/) <--- 404, and join our efforts on [Discord!](http://discord.com/invite/solidjs)

![2023-01-14-22-56-27](https://user-images.githubusercontent.com/3091558/212527446-5ebdb75d-1f20-43f1-9989-7e77c1542843.gif)

**Comment by julian-barker** [comment]
This is an issue with solidjs.com.  The hyperlink directs to https://docs.solidjs.com/tutorials/getting-started-with-solid/ instead of https://docs.solidjs.com/guides/tutorials/getting-started-with-solid/ . The link is correct in the solid-docs code, so I'm not sure what the issue is. Maybe the published version is not the most up-to-date?
