### ISSUE TITLE
Improved Nav Bar 

### ISSUE THREAD

**Issue by Jutanium** [solidjs/solid-docs-next#25]
- Ability to nest "indefinitely"
- The root of a nest must be a page
- Divider lines with titles can be placed anywhere
- Mobile view that doesn't expand the entire TOC

**Comment by crutchcorn** [comment]
Speaking with @Jutanium, we thought of an idea to keep our navbar reflective of:

- Concepts and references in one tab
- How-to guides and tutorials in another tab

But, in order to keep our internal filesystem representative of our [Diataxis](https://diataxis.fr/) methodologies, we should have our routing as:

- `explanations`
- `how-tos`
- `references`
- `tutorials`

Referencing the comparison:

https://github.com/solidjs/solid-docs-next/blob/main/WRITING.md#content-types
