### ISSUE TITLE
Using Solid with Storybook [How-To Guide]

### ISSUE THREAD

**Issue by mnquintana** [solidjs/solid-docs-next#35]
The Storybook API has [changed quite a lot](https://storybook.js.org/docs/react/writing-stories/introduction) since [Solid's Storybook docs](https://github.com/solidui/solid/blob/main/documentation/storybook.md) were written in 2019. It would be really helpful (and I think go a loooong way toward helping drive adoption, long-term) if Solid could:

1. Update the docs to reflect the latest Storybook API (hopefully everything still works with 6.2+?)
2. Abstract all these manual setup steps away with an official Solid framework plugin for Storybook (docs for how to do this here: https://storybook.js.org/docs/react/api/new-frameworks)

Storybook's become a pretty essential piece of the UI development pipeline, and at least for me, official support for it is a prerequisite for seriously considering any frontend frameworks. I miiiight be able to help with setting this up for Solid, although I haven't tried adding support for a new framework to Storybook before. 😅

**Comment by NorbertBodziony** [comment]
What about https://github.com/histoire-dev/histoire they are planing solid support. This seems like great alternative.

**Comment by carere** [comment]
Ok I may have something 😄 

So first here is the button component from the codesandbox example used on this thread:
```ts
import { For } from 'solid-js'

export const Button = ({ count }: { count: number }) => {
  const labels = Array(count)
    .fill(null)
    .map((_, i) => i + 1)

  return <For each={labels}>{label => <button>{label}</button>}</For>
}
```
And then the story
```ts
import { Meta, StoryFn } from '@storybook/html'
import { Component, ComponentProps } from 'solid-js'
import { Button } from '../components/Button'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ComponentStoryFn<T extends Component<any>> = StoryFn<ComponentProps<T>>

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ComponentMeta<T extends Component<any>> = Meta<ComponentProps<T>>

export default {
  title: 'Example/Button',
  argTypes: {
    count: { control: 'number' },
  },
} as ComponentMeta<typeof Button>

const Template = (args => <Button {...args} />) as ComponentStoryFn<typeof Button>

export const Primary = Template.bind({})

Primary.args = {
  count: 5,
}
```
Since, I'm coming from FP land (Rescript), i use `no-explicit-any` rule, but this time, i need to avoid it, else, Typescript gonna prevent me from compiling.
Also, we need to "force cast" the function used during the initialization of Template variable.
If a Typescript wizard has a better and prettier solution to solve this problem, it would be wonderful 😄
Anyway, this is the **up to date** solution to use SolidJS with Storybook

PS: I'm also using vite, the config from the codesandbox for vite, is still correct.

**Comment by elite174** [comment]
If somebody wants to see the repo with examples: https://github.com/elite174/storybook-solid-js

**Comment by JReinhold** [comment]
(Storybook maintainer here 👋)

@elite174 that looks pretty dope actually, and I'm astounded that it works with so little configuration.
Are there any drawbacks with the solution that you know of? Missing features or annoying UX/DX?

If you or anyone else ever want to try and turn this into an actual Solid addon/renderer let me know and I'd be happy to assist you with whatever you need.
I'm also hanging around on the Solid Discord as JReinhold#4884, just ping me.

**Comment by davedbase** [comment]
@elite174 @JReinhold we'd really love for Solid to have an official Storybook adapter. Myself and core will support and provide insight wherever is needed. :heart:

**Comment by elite174** [comment]
Honestly, I prefer framework-agnostic approach. In my repo it's clear enough how to setup storybook with just simple html setup. IMO it would be better if a tool provided plain JS API which can be used by any framework. Just imagine that tommorow there will be Solid-Vue-Svelte super framework and you need to write an integration for it...
I do love how simple it was to setup storybook for solid-js framework. So I'll keep my repo available in case someone wants to use it. I think that integration support costs more than having simple framework-agnostic setup. Maybe it's better to add docs for storybook about how to setup html project with Solid?

@JReinhold All hope is on you :)

**Comment by noahbrenner** [comment]
I was able to get this set up using storybook 7 (currently, `storybook@next`), vite, and the starting points provided in this issue by @grenierdev and @carere:

`.storybook/preview.js` is actually working for me without any decorators defined at all. With the new Storybook version, I initially got an error caused by `document.getElementById("root")` returning null (the decorator was called before that div was created), and eventually pared down the function till I found I could remove it entirely.

I'm staring from the html-vite preset, so `.storybook/main.js` includes this entry:
```javascript
framework: {
  name: "@storybook/html-vite"
  options: {},
}
```

## Story example

These examples use CSF 3.0 - https://storybook.js.org/blog/component-story-format-3-0/

```typescript
// Button.tsx
// `children` would be better than `text`, but I went with this to test the handling of prop types
export function Button({ text }: { text: string }) {
  return <button>{text}</button>;
}
```

```typescript
// Button.stories.tsx
import type {
  ComponentAnnotations,
  StoryAnnotations,
  WebRenderer,
} from "@storybook/types";
import type { Component, ComponentProps } from "solid-js";
import { Button } from "./Button";

// I'm including all these types here, but in a real project, I'd define them in a separate file.
// Only Meta and StoryObj would need to be exported from that file.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyComponent = Component<any>;

interface SolidRenderer extends WebRenderer {
  component: AnyComponent;
  storyResult: ReturnType<AnyComponent>;
}

type Meta<T extends AnyComponent> = ComponentAnnotations<
  SolidRenderer,
  ComponentProps<T>
>;

type StoryObj<T extends AnyComponent> = StoryAnnotations<
  SolidRenderer,
  ComponentProps<T>
>;

// And here's the actual story content

export default {
  title: "MyButton",
  component: Button,
} satisfies Meta<typeof Button>;

export const FooButton: StoryObj<typeof Button> = {
  args: {
    text: "Foo",
  },
};
```

**Comment by carere** [comment]
@noahbrenner Can you share with us your package.json, main.js, and preview.js ?
I remembered, that in order to had a fully working storybook in 6.5, I needed to add way so much dependencies.

**Comment by elite174** [comment]
Guys, storybook 7 is just in beta
I'll make an update to my repo when storybook v7 is released.

**Comment by noahbrenner** [comment]
@carere Absolutely, I'll paste those files below.

The storybook-related dependencies were installed by running `npx storybook@next init --type html` and I haven't made any changes to `preview.js`. I'm sure the storybook addon dependencies could be removed if you don't plan to use them. It seems odd to need react as a direct dependency, but it probably makes sense so that a react project doesn't end up depending on 2 different versions -- one for the project itself and one for storybook. In any case, the react deps were added automatically by the storybook init script.


This isn't a *fully* minimal repro, since I have some non-essential deps (prettier, eslint, husky, lint-staged, vitest, jsdom, tauri), but it *is* still just the initial setup of the project.
<details>
<summary>package.json</summary>

```json
{
  "version": "0.0.0",
  "description": "",
  "license": "MIT",
  "scripts": {
    "prepare": "husky install",
    "start": "vite",
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview",
    "lint": "tsc --noEmit && eslint --ext .ts,.tsx --ignore-path .gitignore . && prettier --check ./*.* src",
    "test": "vitest --reporter=verbose",
    "tauri": "tauri",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "lint-staged": {
    "**/*": "prettier --write --ignore-unknown"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^7.0.0-beta.17",
    "@storybook/addon-interactions": "^7.0.0-beta.17",
    "@storybook/addon-links": "^7.0.0-beta.17",
    "@storybook/blocks": "^7.0.0-beta.17",
    "@storybook/html": "^7.0.0-beta.17",
    "@storybook/html-vite": "^7.0.0-beta.17",
    "@storybook/testing-library": "^0.0.13",
    "@tauri-apps/cli": "^1.2.2",
    "@types/babel__core": "^7.1.20",
    "@types/node": "^18.7.10",
    "@typescript-eslint/eslint-plugin": "^5.47.1",
    "@typescript-eslint/parser": "^5.47.1",
    "eslint": "^8.30.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-storybook": "^0.6.8",
    "husky": "^8.0.2",
    "jsdom": "^20.0.3",
    "lint-staged": "^13.1.0",
    "prettier": "^2.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "storybook": "^7.0.0-beta.17",
    "typescript": "^4.7.4",
    "vite": "^4.0.0",
    "vite-plugin-solid": "^2.3.0",
    "vitest": "^0.26.2"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.2.0",
    "solid-js": "^1.4.7"
  }
}
```

</details>

<details>
<summary>.storybook/main.js</summary>

```javascript
module.exports = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook/html-vite",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
};
```
</details>

<details>
<summary>.storybook/preview.js</summary>

```javascript
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}
```

</details>

And just so everything is in one place, here are the component and story files again:

<details>
<summary>src/components/Button.tsx</summary>

```tsx
export function Button({ text }: { text: string }) {
  return <button>{text}</button>;
}
```

</details>

<details>
<summary>src/components/Button.stories.tsx</summary>

```tsx
import type {
  AnnotatedStoryFn,
  ComponentAnnotations,
  StoryAnnotations,
  WebRenderer,
} from "@storybook/types";
import type { Component, ComponentProps } from "solid-js";
import { Button } from "./Button";

// Types that should eventually be defined in their own file

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyComponent = Component<any>;

interface SolidRenderer extends WebRenderer {
  component: AnyComponent;
  storyResult: ReturnType<AnyComponent>;
}

type Meta<T extends AnyComponent> = ComponentAnnotations<
  SolidRenderer,
  ComponentProps<T>
>;

type StoryObj<T extends AnyComponent> = StoryAnnotations<
  SolidRenderer,
  ComponentProps<T>
>;

type StoryFn<T extends AnyComponent> = AnnotatedStoryFn<
  SolidRenderer,
  ComponentProps<T>
>;

// Meta is the same for both CSF 2 and 3

export default {
  title: "MyButton",
  component: Button,
} satisfies Meta<typeof Button>;

// Using StoryObj (CSF 3)

export const Foo: StoryObj<typeof Button> = {
  args: {
    text: "Foo",
  },
};

// Using StoryFn (CSF 2)

const Template: StoryFn<typeof Button> = (args) => <Button {...args} />;

export const BarButton = Template.bind({});
Bar.args = {
  text: "Bar",
};
```

</details>

**Comment by noahbrenner** [comment]
Ah, it broke down when using a more complex component (the component example using `<For>` that @carere posted), but it worked again using a modified version of @grenierdev's decorator. I'll post that decorator here and update my previous comment to include the decorator.

The important change here is that we're not inserting the created element into the DOM directly, we're just returning the element and letting Storybook handle inserting it.

```jsx
// .storybook/preview.js
import { render } from "solid-js/web"

let disposeStory = () => {};
export const decorators = [
  (Story) => {
    disposeStory();
    const solidRoot = document.createElement("div");
    disposeStory = render(Story, solidRoot);
    return solidRoot;
  },
];

```

**Comment by noahbrenner** [comment]
Still left to solve: hmr updates

- :smile:  If I update the props using the Storybook controls UI, the component updates right away.

- :frowning_face:  If I update the component code itself, I see the hmr update reflected both in the terminal running storybook and in the browser console, but the component itself isn't re-rendered, so the update isn't reflected in the storybook UI unless I refresh the page or switch to a different story. To verify this, I added a `console.log` to both the decorator and the component itself -- both are logged on load and when switching stories, but not when updating the component.

Any ideas on this, @JReinhold? I don't know if this would need to be addressed from the Solid side or the Storybook side.

**Comment by carere** [comment]
I also have the same problem on 7.x and 6.x

**Comment by elite174** [comment]
@carere @noahbrenner 
Guys, seems like I managed to fix the issue with HMR. See my updated repo: https://github.com/elite174/storybook-solid-js#readme

**Comment by fabien-ml** [comment]
@elite174 i've followed your repo instruction and got this error on a pnpm monorepo : 
```bash
Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
```

My components and stories files are all `.tsx`, any idea ?

**Comment by noahbrenner** [comment]
@fabien-ml That's not a lot of info to go on. Since you're getting a syntax error, that doesn't sound like it has to do with the Storybook/Solid integration. It's possible that question might be better suited to StackOverflow or something (along with a minimal repro of your issue, versions you're using, and the command you ran to get that message). As a first step, you might try just running `tsc --noEmit` and/or your linter over your repo to see if you get more specific error messages about the syntax error.

**Comment by fabien-ml** [comment]
> @fabien-ml That's not a lot of info to go on. Since you're getting a syntax error, that doesn't sound like it has to do with the Storybook/Solid integration. It's possible that question might be better suited to StackOverflow or something (along with a minimal repro of your issue, versions you're using, and the command you ran to get that message). As a first step, you might try just running `tsc --noEmit` and/or your linter over your repo to see if you get more specific error messages about the syntax error.

Yeah I underdstand, sorry. I was able to get it work by using the webpack5 builder instead of vite. I don't know why but the problem seem related to the combo of storybook + vite builder + pnpm monorepo
