### ISSUE TITLE
Routing Example not working - obsolete?

### ISSUE THREAD

**Issue by kusnezoff-alexander** [solidjs/solid-docs-next#384]
### Describe the bug

The Example given at https://docs.solidjs.com/guides/how-to-guides/routing-in-solid/solid-router#setup is not working for me.
There is a problem with importing `Routes`: `'"@solidjs/router"' has no exported member named 'Routes'. Did you mean 'Route'? (tsserver 2724)`.

Removing `Routes` altogether fixes the problem. It also doesn't seem very logical to have two wrappers (`<Router>` and `<Routes>` for the `<Route>`-entries). Maybe this is a mistake in the documentation?

### Steps to Reproduce the Bug or Issue

```js
import { Router, Route, Routes } from "@solidjs/router";
```

### Expected behavior

The examples given in the docs should work without errors.

### Additional Context

- An Issue addressing the same error: https://github.com/solidjs/solid-router/issues/76

- Why does SolidJS suggest using both wrappers (`<Router>` and `<Routes>`) if it seems to work also with just `<Router>`?

**Comment by grantralls** [comment]
I have this same issue. I setup my Solid project with the typescript template, I'm using solid 1.8.7 and @solidjs/router 0.10.3

**Comment by iamBijoyKar** [comment]
I am also facing this same issue. I am using solid `1.8.7` and @solidjs/router `0.10.5` with typescript.

**Comment by fromflux** [comment]
Some error with "@solidjs/router": "^0.10.5" and "solid-js": "^1.8.7".

Not sure if change is intentional since Router/Routes pattern exists as composition feature of React Router and can be useful to decouple app from different routers (ex. common use of memorybrowser in tests).
Could be just a missed export when refactoring in https://github.com/solidjs/solid-router/pull/312 when moving from `src/components.tsx` to `src/routers/components.tsx`

**Comment by maulayyacyber** [comment]
same issue

**Comment by SDeLaVida** [comment]
I concur, I have the same issue.

**Comment by sionkim00** [comment]
I'm getting this error as well

**Comment by saverioscagnoli** [comment]
I am getting the same error
