### ISSUE TITLE
Update Solid-Router guide to latest release

### ISSUE THREAD

**Issue by klequis** [solidjs/solid-docs-next#507]
**Doc page**
https://docs.solidjs.com/guides/routing-and-navigation

**Issue description**
Following documentation results in an error

```
Uncaught SyntaxError: The requested module '/node_modules/@solidjs/router/dist/index.jsx' does not provide an export named 'Routes' (at App.jsx:2:10)
```

**Root problem**
The export `Routes` does not exist in `@solidjs/router`

**Suggestion for a fix**
Happy to provide one if you agree the issue is valid.

**Comment by vincentfretin** [comment]
This guide is still on version 0.8.x/0.9.x of the router it seems, there is also still references to Outlet instead of props.children.
Some changes are need to target 0.10.x
https://docs.solidjs.com/routing/migration

**Comment by atilafassina** [comment]
oh no. That's right... need to update this asap!

thank you for reporting!

**Comment by klequis** [comment]
I can take this one.

Regarding the version. It says above `^0.10.x`  Should I used that version even though `0.12.4` is available?

**Comment by atilafassina** [comment]
> I can take this one.
> 
> Regarding the version. It says above `^0.10.x` Should I used that version even though `0.12.4` is available?

First of all, **thank you**!! That's very appreciated.

As a rule-of-thumb, let's always use the latest release for the docs.
I mentioned 0.10 in the title because that's when the breaking changes happened. I'll re-word the title. Sorry for the confusion!


Feel free to go for it, I'll assign the issue to you and mark as **in progress** 

<div align="center">

![let's go!](https://github.com/solidjs/solid-docs-next/assets/2382552/a2903176-d957-4b2e-b6d9-24c457fd7e01)


</div>

**Comment by klequis** [comment]
I compared the 0.9.0 README in `/solid-router` to the current state of the Routing & Navigation guide. It appears the guide is a subset of what is in the README. Is that the intent/spirit of the guide? 

If so I can keep the new doc close to that. Alternatively, I can cover the topics in the README's TOC, leaving out some of the details, such as the tables of props, to keep the current level of brevity.

**Comment by atilafassina** [comment]
> I compared the 0.9.0 README in `/solid-router` to the current state of the Routing & Navigation guide. It appears the guide is a subset of what is in the README. Is that the intent/spirit of the guide?

No, that's a consequence of lack of time.
We identified most people were confused about the v0.9 => v0.10 migration, and because the old docs were showing examples on v0.9 we wanted to act quickly and bring up-to-date content. So I copied what I thought made sense at the time, but I didn't have time to work properly on the content because I had some tasks on the app itself.

> If so I can keep the new doc close to that. Alternatively, I can cover the topics in the README's TOC, leaving out some of the details, such as the tables of props, to keep the current level of brevity.

The plan was to use the repository's Readme as a starting point just so we don't begin with a blank page, but bulk up the examples and explanation in a more thorough way. You don't need to go the whole 100miles with that, but whatever you do will be a plus.

---

I'd be happy if you could:

1. Remove outdated information, like deprecated APIs example (`<Outlet>`, `<Routes>`, and `useRoutes`, ...)

2. Add as much information as your motivation and time allows in terms of better explaining methods (`createAsync` would be my top priority, but it's ok if you prefer something else - We'll take what you can offer)

**Comment by klequis** [comment]
Thank you. That was helpful guidance.

**Comment by klequis** [comment]
Completed
