### ISSUE TITLE
How-To Guide: Debugging Solid

### ISSUE THREAD

**Issue by Jutanium** [solidjs/solid-docs-next#94]
- How to use a debugger statement
- solid-devtools

**Comment by modderme123** [comment]
Suppose you have an effect that you suspect is running too often. For example let's start with an effect that calls a function using store.a. We would expect that this effect only gets rerun when store.a changes, but it is possible our internal function uses some other signal.

```jsx
createEffect(() => {
  someInternalFunction(store.a)
});
```

Let's start by adding a console.log("Updating", store.a) to the effect to see what the issue is.

```jsx
createEffect(() => {
  console.log("Updating", store.a) 
  someInternalFunction(store.a)
});
```

```
Updating 0
Updating 1
Updating 1
Updating 2
```

This could suggest that we have an issue with our effect updating too frequently. While you could inspect someInternalFunction for dependencies, instead, add a debugger statement.


```jsx
createEffect(() => {
  console.log("Updating", store.a) 
  debugger;
  someInternalFunction(store.a)
});
```

Now we will skip the first two breakpoints because we know those are normal. (note that you need devtools open for debugger statements to activate)

![Screen Shot 2022-07-01 at 11 28 35 AM](https://user-images.githubusercontent.com/14153763/176951051-ffacd323-483f-42ab-8ff4-f3c3065ebf1c.png)

Click the left of the two buttons twice.

Now we're going to look through the call stack:
![Screen Shot 2022-07-01 at 11 30 48 AM](https://user-images.githubusercontent.com/14153763/176951668-f89f38d0-5ffc-48b9-b840-df73c02b99b6.png)
(This is a screenshot of me running debugger on file edits, instead of the store example, would need to be updated)

We're looking for files that we recognize, so in my case I'm looking at `index.tsx` `repl.tsx` and `edit.tsx`. 

In my case: Clicking on those files tells me what triggered this effect: I modified a file and that updated a file source signal, which triggered a sync to monaco
